#Peter Dinh
#What'sMyMeal
#April 25, 2022

from telegram import *
from telegram.ext import *
import constants as keys
#import Responses as R 
import random


print("Bot started...")

#commands 
def start_command(update, context):
    update.message.reply_text(   
        "Hi! I am Mr. Chef, thank you for using my program, What'sMyMeal.\n"
        "Just tell me what you need and I will find you a recipe!\n"     
        "You can use the following commands to talk to me:\n"
        "The following commands are:\n"
        "/Help\n"
        "/Recipes\n"
        "/Vegan\n"
        "/Cocktail")


Pork = 'Pork'
Beef = 'Beef'
Chicken = 'Chicken'
Pasta = 'Pasta'
Taco = 'Taco'
Seafood = 'Seafood'
Salad = 'Salad'
Burger = 'Burger'
Steak = 'Steak'

CHOOSING, TYPING_REPLY, TYPING_CHOICE = range(3)
reply_keyboard = [
    ['Pork', 'Beef', 'Chicken', 'Pasta', 'Taco'],
    ['Seafood', 'Salad', 'Burger', 'Steak'],
    ['Done'],
]
markup = ReplyKeyboardMarkup(reply_keyboard, one_time_keyboard=True)


def recipes_command(update, context):
    update.message.reply_text(
        "Yes, what would you like to eat?",
        reply_markup=markup,
    )
    return CHOOSING
    #food_item = input('What would you like to eat?')
    #pprint.pprint(get_recipe(food_item))



def help_command(update, context):
    update.message.reply_text(
        "Commands:\n"
        "\t/Recipes  -> select any meal to get random recommendation of recipe \n"
        "\t/Vegan -> generate a random vegan recipe \n"
        "\t/Cocktails -> generate a random recipe for a cocktail \n"
    )

vegans = ["Ultimate Tofu Breakfast Burrito Bowls: \n SERVINGS: 3 \n INGREDIENTS: \n 3 tablespoons olive oil, divided \n 1 (14 ounce) package extra-firm tofu, drained \n 1/2 teaspoon salt \n black pepper to taste \n 1 & 1/2 teaspoons onion powder \n 1 & 1/2 teaspoons garlic powder \n 1/2 teaspoon ground turmeric \n 1 tablespoon fresh lemon juice \n 1 tablespoon olive oil \n 1 cup finely diced red onion \n 2 jalapeno peppers, seeded and chopped \n 1/2 teaspoon salt \n 3 cloves garlic, minced \n 2 cups chopped tomatoes \n 1 & 1/2 teaspoons cumin \n 1/4 cup chopped fresh cilantro \n 1 tablespoon fresh lemon juice \n 1 (15.5 ounce) can no-salt-added black beans, drained and rinsed \n 1 & 1/2 cups cooked hash brown potatoes \n 1 avocado - peeled, pitted and sliced \n 1 teaspoon fresh lemon juice \n 1/4 cup chopped fresh cilantro \n 1 teaspoon hot sauce, or to taste \n DIRECTIONS: \n Preheat a large, heavy skillet over medium-high heat. Add 2 tablespoons oil. Break tofu apart over skillet into bite-size pieces, sprinkle with salt and pepper, then cook, stirring frequently with a thin metal spatula, until liquid cooks out and tofu browns, about 10 minutes. (If you notice liquid collecting in pan, increase heat to evaporate water.) Be sure to get under the tofu when you stir, scraping the bottom of the pan where the good, crispy stuff is and keeping it from sticking. Add onion and garlic powders, turmeric, juice, and remaining tablespoon oil and toss to coat. Cook 5 minutes more. Preheat a heavy-bottomed saucepan over medium-high heat. Add oil. Cook onion and jalapenos with a pinch of salt, stirring, until translucent, about 5 minutes, Add garlic and cook, stirring, until fragrant, about 30 seconds. Add tomatoes, cumin, and remaining salt, and cook, stirring, until tomatoes become saucy, about 5 minutes. Add cilantro and lemon juice. Let cilantro wilt in. Add beans and heat through, stirring occasionally, about 2 minutes. Taste for salt and seasoning. Spoon some hash browns into each bowl, followed by a scoop of beans and a scoop of scramble. Top with avocado, a squeeze of fresh lemon juice, and a sprinkle of cilantro. Serve with hot sauce.",
         "Couscous with Olives and Sun-Dried Tomato: \n SERVINGS: 4 \n INGREDIENTS: \n 1 & 1/4 cups vegetable broth \n 1 & 1/4 cups water \n 2 cups pearl (Israeli) couscous \n 1 pinch salt \n 1 pinch ground black pepper \n 5 tablespoons olive oil, divided \n1/2 cup pine nuts \n 4 cloves garlic, minced \n 1 shallot, minced \n 1/2 cup sliced black olives \n 1/3 cup sun-dried tomatoes packed in oil, drained and chopped \n 1 cup vegetable broth \n 1/4 cup chopped fresh flat-leaf parsley \n DIRECTIONS: \n Bring 1 1/4 cup vegetable broth and water to a boil in a saucepan, stir in couscous, and mix in salt and black pepper. Reduce heat to low and simmer until liquid is absorbed, about 8 minutes. Heat 3 tablespoons olive oil in a skillet over medium-high heat; stir in pine nuts and cook, stirring frequently, until pine nuts smell toasted and are golden brown, about 1 minute. Remove from heat. Heat remaining 2 tablespoons olive oil in a saucepan; cook and stir garlic and shallot in the hot oil until softened, about 2 minutes. Stir black olives and sun-dried tomatoes into garlic mixture and cook until heated through, 2 to 3 minutes, stirring often. Slowly pour in 1 cup vegetable broth and bring mixture to a boil. Reduce heat to low and simmer until sauce has reduced, 8 to 10 minutes. Transfer couscous to a large serving bowl, mix with sauce, and serve topped with parsley and pine nuts.",
         "Breaded, Fried, Softly Spiced Tofu: \n SERVINGS: 4 \n INGREDIENTS: \n 1 (16 ounce) package extra-firm tofu, drained and pressed \n 2 cups vegetable broth \n 3 tablespoons vegetable oil \n 1/2 cup all-purpose flour \n 3 tablespoons nutritional yeast \n 1 teaspoon salt \n 1/2 teaspoon freshly ground black pepper \n 1 teaspoon sage \n 1/2 teaspoon cayenne pepper \n DIRECTIONS: \n Cut pressed tofu into 1/2-inch thick slices; then cut again into 1/2-inch wide sticks. Place tofu in a bowl, and pour broth over the top. Set aside to soak. In a separate bowl, stir together flour, yeast, salt, pepper, sage, and cayenne. Warm oil in a large skillet over medium-high heat. Remove tofu sticks from broth, and squeeze most (but not all) of the liquid from them. Roll sticks in breading. (You may have to roll sticks twice to end up with a fairly dry outer layer of breading.) Place tofu in hot oil; fry until crisp and browned on all sides. Add more oil if necessary.",
          "Butternut Squash Stuffed Shells: \n SERVINGS: 4 \n INGREDIENTS: \n 1 & 1/2 cups cubed butternut squash \n extra-virgin olive oil, for drizzling \n 16 jumbo shells /n FOR CASHEW CREAM \n 1 & 1/2 cups raw cashews*, see note \n 1 cup fresh water \n 1 garlic clove \n 3 & 1/2 tablespoons fresh lemon juice \n 1/2 teaspoon sea salt \n freshly ground pepper \n FOR FILLING \n 4 cups fresh baby spinach \n 1 cup crumbled firm tofu \n 1 teaspoon dried oregano \n 1/2 teaspoon lemon zest \n pinch of red pepper flakes \n 1 cup cashew cream, from the recipe above \n sea salt and freshly ground pepper \n DIRECTIONS: \n Preheat the oven to 350°F and line a baking sheet with parchment paper. Toss the butternut squash with a drizzle of olive oil and a few generous pinches of salt and pepper. Roast until golden brown, 20 to 25 minutes. Make the cashew cream: Blend together the drained raw cashews, fresh water, garlic, lemon juice, 1/2 teaspoon salt and pepper. Make the filling: In a medium skillet, heat a drizzle of olive oil over medium heat. Add the spinach in increments, along with a pinch of salt, and sauté until all the spinach is incorporated and wilted. Remove from heat and let cool slightly. Squeeze out any excess liquid and chop. In a medium bowl, combine the the spinach with the crumbled tofu, oregano, lemon zest, red pepper flakes, at least 1/4 teaspoon salt, freshly ground black pepper and 1 cup of cashew cream. Season to taste, adding more salt and pepper as desired. Bring a large pot of salted water to a boil. Add the shells and cook according to the package directions until al dente. Drain. Assemble the shells. Spread ¼ cup of the reserved cashew cream on the bottom of an 11x7-inch baking dish. Fill each cooked shell with some of the filling and a few cubes of butternut squash, and place into the baking dish. Drizzle a little olive oil over the shells, cover with foil, and bake for 15 minutes, or until heated through. Remove from the oven and serve with the remaining cashew cream.", 
          "Chipotle Cauliflower Nachos: \n SERVINGS: 4-6 \n INGREDIENTS: \n CHIPOTLE CAULIFLOWER 'CHEESE' SAUCE: \n 1 cup chopped cauliflower \n 1 cup peeled and cubed Yukon gold potato \n 1/4 cup raw cashews \n 3 tablespoons water, more as needed \n 2 tablespoons apple cider vinegar \n 2 tablespoons olive oil \n 1 chipotle pepper from a can of chipotles in adobo* \n 1 garlic clove \n 1/2 teaspoon onion powder \n 1/2 teaspoon sea salt \n FOR THE NACHOS: \n Tortilla chips \n 1/2 cup diced cherry tomatoes \n 1/3 cup cooked black beans, drained and rinsed \n 1/2 cup Pineapple Salsa \n 1/4 cup diced red onion \n 1/4 cup chopped cilantro \n DIRECTIONS: \n Make the sauce: Place the cauliflower and potatoes in a medium saucepan and cover with cold water by about 1-inch. Add a pinch of salt. Bring to a boil, then reduce the heat to a simmer and cook uncovered until fork-tender, 8 to 10 minutes. Drain, let cool slightly, then place in a high-speed blender with the cashews, water, apple cider vinegar, olive oil, chipotle pepper, garlic, onion powder, and salt. Blend until smooth. Spread the chips onto a platter, drizzle with the chipotle cauliflower sauce, and top with the cherry tomatoes, black beans, scoops of pineapple salsa, red onion, and the cilantro. Serve and enjoy!"
          ]

vegan_jokes = ["Can I tell you a vegan joke? I promise it won't be cheesy!", "Being a vegan is a big MISSED STEAK", "You're vegan? Where do you get your proteins? Oh wait, plants has protiens...."]

def vegan_command(update, context):
    update.message.reply_text(random.choice(vegan_jokes))
    update.message.reply_text(random.choice(vegans))

cocktails = ["Manhattan: \n INGREDIENTS: \n 2 ounces rye whiskey \n 1 ounce sweet vermouth \n 2 dashes Angostura bitters \n 1 dash orange bitters \n Garnish: brandied cherry or lemon twist \n DIRECTIONS: \n Add the bourbon (or rye), sweet vermouth and both bitters to a mixing glass with ice, and stir until well-chilled. Strain into a chilled coupe. Garnish with a brandied cherry or a lemon twist.", 
            "Mojito: \n INGREDIENTS: \n 3 mint leaves \n 1/2 ounce simple syrup \n 2 ounces white rum \n 3/4 ounce lime juice, freshly squeezed \n Club soda, to top \n Garnish: mint sprig \n Garnish: lime wheel \n DIRECTIONS: \n Lightly muddle the mint with the simple syrup in a shaker. Add the rum, lime juice and ice, and give it a brief shake, then strain into a highball glass over fresh ice. Alternatively, you can use pebble ice instead and gently swizzle it all together. Top with the club soda. Garnish with a mint sprig and lime wheel.", 
            "Hommade Cinnamon Whiskey: \n INGREDIENTS: \n 1 (750 mL) bottle inexpensive whiskey \n 8 cinnamon sticks \n 3 ounces simple syrup \n 6 whole dried red chile peppers (optional) \n DIRECTIONS: \n Empty the bottle of whiskey into a large container with a lid. Add the cinnamon sticks and simple syrup and seal. Shake the container and let stand for five days, shaking daily. After five days, add the dried chile peppers to the container, if desired, and shake again. Let stand for three to four more days, tasting after the first day to test the flavor intensity. When the flavor reaches the desired intensity, strain and rebottle.",
            "Best Whiskey Sour: \n INGREDIENTS: \n 2 ounces (4 tablespoons) bourbon whiskey* \n 1 ounce (2 tablespoons) fresh lemon juice \n 3/4 ounce (1 & 1/2 tablespoons) pure maple syrup (or simple syrup) \n Garnish: Orange peel and a cocktail cherry \n Ice, for serving \n DIRECTIONS: \n Add the bourbon whiskey, lemon juice, and syrup to a cocktail shaker. Fill with a handful of ice and shake until very cold. Strain the drink into a lowball or Old Fashioned glass. Serve with ice, an orange peel and a cocktail cherry. ", 
            "Aperol Spritz: \n INGREDIENTS: \n 2 ounces (4 tablespoons) Aperol, chilled \n 3 ounces (6 tablespoons) Prosecco or other sparkling wine, chilled \n 1 ounce (2 tablespoons) soda water \n Ice (try clear ice!) \n For the garnish: orange wedge, a straw if you like \n DIRECTIONS:\n Add the Aperol to a glass filled with ice and stir. Top with the sparkling wine and soda water. Squeeze in the orange wedge and stir gently, then serve. Serve with a straw to minimize dilution!"
            "Moscow Mule: \n INGREDIENTS: \n 2 ounces (¼ cup) vodka \n 1/2 ounce (1 tablespoon) fresh lime juice \n 4 ounces (1/2 cup) ginger beer \n For the garnish: lime wheel or wedge, fresh mint (if desired) \n DIRECTIONS: \n In a copper mug or glass, pour in the vodka, lime juice, and ginger beer. Add ice and garnish with a lime slice. Serve immediately.", ]

def cocktail_command(update, context):
    update.message.reply_text("Long day? Or need to celebrate? Well here you go!")
    update.message.reply_text(random.choice(cocktails))
    update.message.reply_text("Please drink responsibly and no under age drinking within the Jurisdiction!")

porks =["Instant Pot Baby Back Ribs: \n SERVINGS: 4 \n INGREDIENTS: \n 2 tablespoons kosher salt \n 1 tablespoon brown sugar \n 1 tablespoon chili powder \n 1 tablespoon paprika \n 2 teaspoons garlic powder \n 1 & 1/2 teaspoons cayenne pepper \n 1 teaspoon ground black pepper \n 1 rack baby back pork ribs \n 1 cup beef broth \n 1/4 cup barbeque sauce, or as needed \n DIRECTIONS: \n Combine kosher salt, brown sugar, chili powder, paprika, garlic powder, cayenne pepper, and black pepper in a small bowl for the spice rub. Cut the rack of ribs into 4 equal portions. Rub all sides of each piece with spice rub. Pour broth into a multi-functional pressure cooker (such as Instant Pot®). Add ribs in a teepee formation. Close and lock the lid. Select high pressure according to manufacturer's instructions; set timer for 30 minutes. Allow 10 to 15 minutes for pressure to build. Preheat the oven to 425 degrees F (220 degrees C). Line a baking sheet with aluminum foil. Release pressure carefully using the quick-release method according to manufacturer's instructions, about 5 minutes. Unlock and remove lid. Move ribs to the baking sheet using tongs. Brush ribs on all sides with barbeque sauce. Bake in the preheated oven for 7 minutes. Turn ribs and continue baking until meat pulls away easily from the bone, about 7 minutes more. An instant-read thermometer inserted into the center should read 145 degrees F (63 degrees C).",
         "Pork Chops with Apple Cider Glaze: \n SERVINGS: 6 \n INGREDIENTS: \n 6 (6 ounce) boneless center-cut pork chops \n salt and ground black pepper to taste \n 1 tablespoon vegetable oil \n 1 tablespoon butter \n 3 cloves garlic, minced \n 1/4 cup apple cider vinegar \n 2 cups apple cider \n 1 teaspoon Dijon mustard \n 1 teaspoon minced rosemary \n 1 pinch red pepper flakes \n DIRECTIONS: \n Season pork chops with salt and black pepper. Heat oil and butter in a heavy skillet over medium-high heat. Cook pork chops in the hot oil mixture until browned on both sides and pork is slightly pink in the center, 5 to 7 minutes per side. An instant-read thermometer inserted into the center should read at least 145 degrees F (63 degrees C). Remove pan from the heat; transfer pork chops to a plate. Stir garlic into the pan and place over medium-high heat; cook and stir for 30 seconds. Pour in vinegar and scrape up any browned bits from the bottom of the pan. Add apple cider and Dijon mustard, bring mixture to a boil, and cook until sauce is reduced and thick, 3 to 4 minutes. Stir in rosemary and red pepper flakes; season with salt and black pepper to taste. Return pork chops to the pan to warm slightly, 1 to 2 minutes per side.",
         "Creamy Herbed Pork Chops: \n SERVINGS: 4 \n INGREDIENTS: \n 4 thick-cut pork chops \n 1 teaspoon Montreal steak seasoning, or to taste \n 1/2 cup butter, divided \n 2 1/2 tablespoons all-purpose flour, or as needed \n 1 tablespoon dried basil \n 1 teaspoon instant beef bouillon granules \n 1 teaspoon freshly ground black pepper \n 2 cups milk \n DIRECTIONS: \n Season pork chops on all sides with Montreal steak seasoning. Melt 2 tablespoons butter in a large skillet over medium heat. Cook chops in melted butter until browned and slightly pink in the center, about 7 to 10 minutes per side. An instant-read thermometer inserted into the center should read at least 145 degrees F (63 degrees C). Add remaining butter to the pan as needed so that about 3 tablespoons pan drippings remain in the pan when the chops are finished cooking. Transfer pork chops to a plate and return skillet to medium-high heat. Mix flour, basil, and beef bouillon together in a bowl. Stir black pepper into skillet with the pan drippings and cook for 1 minute. Add flour mixture and cook, stirring constantly, until browned, about 2 minutes. Pour milk into flour mixture; cook and stir constantly until mixture is thick and bubbly, 4 to 6 minutes. Pour sauce over pork chops and serve."
        ]

beefs = ["Korean Beef: \n SERVINGS: 15, \n INGREDIENTS: \n 2 tablespoons toasted sesame seed,\n 1/3 cup  soy sauce,\n 2 tablespoons sake -- (or dry vermouth),\n 1 tablespoon molasses,\n 1 teaspoon toasted sesame oil,\n 1/4 teaspoon  pepper,\n 1 & 1/2 pounds  beef sirloin steak -- boneless, in 1 inch cubes skewers -- 4 to 6 inches toasted white and black sesame seed white radish relish,\n DIRECTIONS: \n Based on the classic Korean entree made with beef short ribs, this easier-to-eat appetizer features beef sirloin. Blend the 2 tablespoons toasted sesame seed in a covered blender container till ground. 2 Transfer to a small bowl; stir in soy sauce, sake, sesame oil and pepper. Place beef cubes in a heavy plastic bag; add marinade. Seal bag and turn to coat. Chill for 2-4 hours turning bag occasionally. Meanwhile soak wooden skewers in water for 30 minutes. Drain meat, reserving the marinade. Thread two meat cubes onto each skewer. Place skewers on the rack of an unheated broiler pan; broil 3-4 inches from the heat for 12-14 minutes or till done, turning once and brushing with reserved marinade. Arrange skewers on a serving plate. Sprinkle with toasted white and black sesame seed. Serve with White Radish Relish. Makes 18 servings.", 
        "Spaghetti Sauce with Ground Beef: \n SERVINGS: 8 \n INGREDIENTS: \n 1 pound ground beef\n 1 medium onion, chopped\n 4 cloves garlic, minced\n 1 small green bell pepper, diced\n 1 (28 ounce) can diced tomatoes\n 1 (16 ounce) can tomato sauce\n 1 (6 ounce) can tomato paste\n 2 teaspoons dried oregano\n 2 teaspoons dried basil\n 1 teaspoon salt\n 1/2 teaspoon ground black pepper\n DIRECTIONS: \n Combine ground beef, onion, garlic, and green pepper in a large saucepan over medium-high heat. Cook and stir until meat is browned and crumbly and vegetables are tender, 5 to 7 minutes. Drain grease. Stir diced tomatoes, tomato sauce, and tomato paste into the pan. Season with oregano, basil, salt, and pepper. Simmer spaghetti sauce for 1 hour, stirring occasionally.",
        "Shepherd's Pie: \n SERVINGS: 4, \n INGREDIENTS: \n 1-1/2 pounds ground beef \n 1 medium onion, chopped \n 2 garlic cloves, minced \n 1/2 cup water \n 1 envelope taco seasoning \n 2 cups shredded cheddar cheese, divided \n 3 cups leftover or refrigerated mashed potatoes, warmed \n DIRECTIONS: \n Preheat broiler. In a large ovenproof skillet, cook beef, onion and garlic over medium heat until beef is no longer pink, breaking up beef into crumbles; drain. Stir in water and taco seasoning; heat through. Stir in 1 cup cheese. Remove from heat. In a bowl, mix mashed potatoes and remaining cheese; spread over beef mixture. Broil 4-6 in. from heat 5-6 minutes or until top is golden brown. "       
        ]

chickens = [ "Honey-Garlic Slow Cooker Chicken Thighs: \n SERVINGS: 4 \n INGREDIENTS: \n 4 skinless, boneless chicken thighs \n 1/2 cup soy sauce \n 1/2 cup ketchup \n 1/3 cup honey \n 3 cloves garlic, minced \n 1 teaspoon dried basil \n DIRECTIONS: \n Lay chicken thighs into the bottom of a 4-quart slow cooker. Whisk soy sauce, ketchup, honey, garlic, and basil together in a bowl; pour over the chicken. Cook on Low for 6 hours.", 
         "Rusty Chicken Thighs: \n SERVINGS: 8 \n INGREDIENTS: \n 1 clove garlic, sliced, or more to taste \n 2 teaspoons Asian chile pepper sauce (such as sambal oelek), or more to taste \n 1 & 1/2 tablespoons maple syrup \n 2 tablespoons soy sauce \n 2 tablespoons mayonnaise \n 3 tablespoons rice vinegar \n salt and freshly ground black pepper to taste \n 2 pounds skinless, boneless chicken thighs \n 1 lime, cut into 8 wedges \n DIRECTIONS: \n Mash garlic to a paste with a mortar and pestle. Mix chile pepper sauce, maple syrup, soy sauce, mayonnaise, and rice vinegar into garlic until marinade is thoroughly combined. Transfer chicken thighs to a large flat container (such as a baking dish) and pour marinade over chicken; stir until chicken is coated. Cover dish with plastic wrap and refrigerate about 3 hours; if preferred, let stand about 30 minutes at room temperature. Unwrap dish and sprinkle with salt. Preheat charcoal grill to high heat. Place chicken thighs onto the hot grill with smooth sides down. Cook until chicken shows grill marks, about 3 minutes. Turn chicken over and cook until other side shows grill marks, about 5 minutes. Continue to cook, moving them occasionally and turning over every 2 minutes, until meat is no longer pink inside and the thighs are golden brown, 10 to 12 minutes. Transfer chicken to a platter, let rest for 5 minutes, and serve garnished with lime wedges.",
         "Crispy Rosemary Chicken and Fries: \n SERVINGS: 6 \n INGREDIENTS: \n 8 chicken thighs \n 6 small red potatoes, quartered \n 1/2 cup extra-virgin olive oil, or as needed \n 1 tablespoon chopped fresh rosemary \n 1 & 1/2 teaspoons chopped fresh oregano \n 1 & 1/2 teaspoons garlic powder \n salt and pepper to taste \n DIRECTIONS: Preheat the oven to 375 degrees F (190 degrees C). Place chicken and potatoes into a large bowl. Pour olive oil over them, and stir to coat. Scatter the chicken and potato pieces in a large baking dish, or cookie sheet with sides. Sprinkle with rosemary, oregano, garlic powder, salt and pepper. Bake for 1 hour in the preheated oven, uncovered. Baste during the last 15 minutes for extra crispness."
        ]
pastas = ["Spaghetti with Sun-Dried-Tomato-Almond Pesto: \n SERVINGS: 4 \n INGREDIENTS: \n 1/2 cup drained oil-packed sun-dried tomatoes (3 ounces) \n 1/3 cup salted roasted almonds \n 1 large garlic clove \n 1/2 cup extra-virgin olive oil \n Salt and freshly ground pepper \n 1/2 cup fresh bread crumbs \n 12 ounces spaghetti \n 2 tablespoons chopped parsley \n DIRECTIONS: \n In a food processor, pulse the tomatoes, almonds and garlic. Add 1/4 cup of the oil and puree. Season with salt and pepper. In a skillet, toast the bread crumbs in 2 tablespoons of the oil, stirring, until golden. Transfer the crumbs to a plate; season with salt and pepper. In a large pot of boiling salted water, cook the pasta until al dente. Drain, reserving 1/2 cup of the cooking liquid. In the pot, toss the pasta with the pesto, reserved cooking water and remaining 2 tablespoons of oil until the sauce clings to the pasta. Transfer the pasta to bowls, sprinkle with the bread crumbs and parsley and drizzle with olive oil. Serve.",
         "Cheese Tortellini with Walnut Pesto: \n SERVINGS: 4 \n INGREDIENTS: \n 1 cup walnuts \n 1/3 cup lightly packed flat-leaf parsley with thick stems removed \n 2 cloves garlic (smashed) \n 3 tablespoons grated Parmesan cheese (plus more for serving) \n 1/2 cup olive oil \n 1/2 teaspoon salt \n 1/4 teaspoon fresh-ground black pepper \n 1 pound fresh or frozen cheese tortellini \n 1 tablespoon butter \n DIRECTIONS: \n In a food processor or blender, pulse the walnuts, parsley, garlic, Parmesan, oil, salt, and pepper to a coarse puree. In a large pot of boiling, salted water, cook the tortellini until just done, about 4 minutes for fresh and 12 minutes for frozen. Reserve 1/2 cup of the pasta water. Drain the tortellini. Toss with 1/4 cup of the reserved pasta water, the walnut pesto, and the butter. If the pasta seems dry, add more of the reserved pasta water. Sprinkle with additional Parmesan and pass more at the table.",
         "Crab Macaroni Gratin: \n SERVINGS: 6-8 \n INGREDIENTS: \n 8 ounces uncooked medium pasta shells (about 3 cups) \n 4 ounces white cheddar cheese, finely shredded (about 1 cup) \n 3 ounces Gruyère cheese, finely shredded (about 3/4 cup) \n 3 ounces Parmigiano-Reggiano cheese, grated (about 3/4 cup) \n 2 1/2 cups heavy cream \n 1 medium garlic glove, finely chopped \n 12 ounces fresh Dungeness crabmeat (about 2 cups), picked over \n 5 tablespoons thinly sliced fresh chives, divided \n Fine sea salt, to taste \n DIRECTIONS: Cook pasta in boiling salted water according to package directions for al dente. Drain. Meanwhile, toss together cheddar, Gruyère, and Parmigiano-Reggiano until well combined; set aside 1 cup cheese mixture. Preheat broiler to low with oven rack in top third of oven. Bring cream just to a boil in a large saucepan over medium-high. Reduce heat to low; add garlic, and gently simmer, stirring often, 2 minutes. Stir in cooked pasta, and return to a gentle simmer over medium. Cook, stirring often, 1 minute. Reduce heat to medium-low. Stir in cheese mixture in three additions (about 1 1/2 cups at a time), until cheese is melted after each addition. Gently stir in crab and 1/4 cup chives. Season to taste with salt. Spoon pasta mixture into an 8- x 6- x 2-inch broiler-proof baking dish set on a rimmed baking sheet. Top with reserved 1 cup cheese mixture in an even layer. Broil in preheated oven until cheese is golden brown and crusty, 5 to 7 minutes, rotating as needed for even browning. Let stand 5 to 10 minutes, and sprinkle with remaining 1 tablespoon chives."
      ]
tacos = ["Birria Tacos: \n SERVINGS: 16 tacos \n INGREDIENTS: \n 1 (2-pound) boneless chuck roast (about 2 1/4 inches thick) \n 2 pounds English-cut beef short ribs (about 3 ribs) \n 2 tablespoons plus 1/4 teaspoon kosher salt, divided, plus more to taste \n Adobo \n 8 cups water \n 1 cup finely chopped white onion, rinsed \n 1/3 cup finely chopped fresh cilantro \n Canola oil, for greasing \n 32 (6-inch) fresh corn tortillas or 16 packaged corn tortillas \n Lime wedges, for serving \n DIRECTIONS: \n Sprinkle chuck roast and short ribs all over with 2 tablespoons salt. Combine roast, ribs, and adobo in a large nonreactive bowl; toss to coat. Cover and chill at least 4 hours or up to 24 hours. Preheat oven to 300°F. Transfer adobo mixture to a large (9 1/2-quart) Dutch oven; add 8 cups water. Bring to a simmer, uncovered, over medium, stirring occasionally. Cover with lid, and place in preheated oven. Bake until meat is fork- tender, about 4 hours. Remove chuck roast and short ribs from braising broth, and transfer to a large bowl; cover with aluminum foil to keep warm. Return broth in Dutch oven to heat over medium, and cook, uncovered, skimming off fat as needed, until reduced to about 8 cups, 15 to 20 minutes. Season broth with salt to taste. Shred meat; discard bones. Toss meat with 1 1/2 cups of the broth. Stir together onion, cilantro, and remaining 1/4 teaspoon salt in a small bowl; set aside. Heat a large nonstick electric griddle to 400°F or a large (12-inch) cast-iron skillet over medium-high. Using a paper towel dipped in canola oil, lightly grease griddle. If using fresh tortillas, stack 2 tortillas, and use tongs to dip them together into adobo broth. (If using packaged tortillas, dip 1 tortilla per taco.) Place stacked tortillas on griddle; top with 1/4 cup meat. Repeat with as many tortilla stacks as will comfortably fit on griddle. Cook until bottom tortilla is lightly browned and crispy, 1 to 2 minutes. Fold tacos in half, gently pressing with a spatula. Transfer to a serving plate. Repeat process with oil, adobo broth, remaining tortillas, and remaining meat. Serve tacos hot with onion-cilantro mixture, lime wedges, and remaining adobo broth for dipping or sipping.", 
         "Barbacoa Beef Tacos with Two Sauces: \n SERVINGS: 6 \n INGREDIENTS: \n 4 large ancho chiles, stemmed and seeded \n 4 dried chipotle chiles, stemmed \n 3 celery ribs, chopped \n 2 medium carrots, chopped \n 1 large onion, halved and thinly sliced \n 15 garlic cloves, crushed and peeled \n 8 bay leaves \n Six 1-lb., English-cut, bone-in beef short ribs \n 2 tablespoons dried oregano \n 1/2 teaspoon ground cumin \n Kosher salt \n Pepper \n Warm corn tortillas, cilantro sprigs, finely chopped white onion and lime wedges, for serving \n Salsa Verde Cruda, for serving \n DIRECTIONS: \n BRAISE THE MEAT \n Preheat the oven to 325°. In a medium skillet, toast the ancho chiles over moderate heat, turning, until pliable and charred in spots, about 2 minutes; let cool slightly, then tear into pieces. \n In a large roasting pan, toss the ancho and chipotle chiles with the celery, carrots, onion, garlic and bay leaves. In a large bowl, toss the short ribs with the oregano, cumin and 2 tablespoons of salt. Arrange the ribs over the vegetables in the roasting pan. Add 2 cups of water to the pan, cover tightly with foil and braise in the oven for about 3 1/2 hours, until the meat is very tender. \n MAKE THE CHILE SAUCE \n Transfer the ribs to a baking sheet. Strain the braising liquid through a colander set over a heatproof bowl; skim off any fat. Discard the bay leaves and return the vegetables and chiles to the braising liquid. Working in batches, puree the vegetables and liquid in a blender until smooth. Season the sauce with salt and pepper. \n GRILL \n Light a grill or preheat a grill pan. Working in batches if necessary, grill the ribs over high heat, turning occasionally, until charred and crisp, about 5 minutes total. Transfer to a platter and, using two forks, shred the meat; discard the bones. Serve the barbacoa in warm corn tortillas with the sauce, cilantro, chopped onion, lime wedges and Salsa Verde Cruda.", 
         "Taco al Pastor: \n SERVINGS: 12 TACOS \n INGREDIENTS: \n 4 dried guajillo chiles (about 1 ounce) \n 1 dried ancho chile \n 2 dried chipotle chiles \n 2 tablespoons fresh orange juice \n 1/2 tablespoon fresh lime juice \n 1/4 cup Coca-Cola \n 3 tablespoons cider vinegar \n 1 teaspoon annatto seeds \n 1/2 teaspoon dried oregano \n 1/4 teaspoon cumin seeds \n 1 whole clove \n 1/2 tablespoon brown sugar \n 1/4 teaspoon garlic powder \n 2 tablespoons vegetable oil, plus more for grilling \n 2 1/2 pounds boneless pork shoulder, cut into 1/2-inch-thick slices \n 1 large Spanish onion, cut into 1/2-inch-thick slices \n Salt and freshly ground pepper \n 12 corn tortillas, warmed \n Grilled pineapple, chopped red onion and cilantro, for serving \n DIRECTIONS: \n Stem and seed all of the dried chiles and place them in a microwave-safe bowl. Cover with water and microwave at high power until softened, about 3 minutes. Let cool slightly, then drain and transfer to a blender. Add the orange juice, lime juice, soda and vinegar. In a spice grinder, grind the annatto with the oregano, cumin, clove, sugar and garlic powder until fine. Add the spice mixture to the blender and blend until smooth. Transfer the marinade to a saucepan. Add the 2 tablespoons of oil and cook over moderate heat, stirring constantly, until very thick, about 5 minutes; let cool. Transfer the marinade to a large resealable plastic bag. Add the pork and onion and seal the bag. Refrigerate overnight. Light a grill. Remove the pork and onion from the marinade and scrape most of it off. Brush the pork and onion with oil and season with salt and pepper. Grill over moderate heat, turning, until the meat is cooked through, 15 minutes. Transfer the pork and onion to a work surface, cover loosely with foil and let stand 10 minutes. Cut the pork into strips. Serve the pork and onion with the warmed tortillas, grilled pineapple, red onion and cilantro."
        ]

seafoods = ["New Orleans Creole Gumbo: \n SERVINGS: 20 \n INGREDIENTS: \n 1 cup all-purpose flour \n 3/4 cup bacon drippings \n 1 cup coarsely chopped celery \n 1 large onion, coarsely chopped \n 1 large green bell pepper, coarsely chopped \n 2 cloves garlic, minced \n 1 pound andouille sausage, sliced \n 3 quarts water \n 6 cubes beef bouillon \n 1 tablespoon white sugar \n salt to taste \n 2 tablespoons hot pepper sauce (such as Tabasco®), or to taste \n 1/2 teaspoon Cajun seasoning blend (such as Tony Chachere's®), or to taste \n 4 bay leaves \n 1/2 teaspoon dried thyme leaves \n 1 (14.5 ounce) can stewed tomatoes \n 1 (6 ounce) can tomato sauce \n 4 teaspoons file powder, divided \n 2 tablespoons bacon drippings \n 2 (10 ounce) packages frozen cut okra, thawed \n 2 tablespoons distilled white vinegar \n 1 pound lump crabmeat \n 3 pounds uncooked medium shrimp, peeled and deveined \n 2 tablespoons Worcestershire sauce \n DIRECTIONS: \n ROUX: \n Whisk together flour and 3/4 cup bacon drippings in a large, heavy saucepan over medium-low heat until smooth. Cook roux, whisking constantly, until it turns a rich mahogany brown color. This can take 20 to 30 minutes; watch heat carefully and whisk constantly or roux will burn. Remove from heat; continue whisking until mixture stops cooking. \n GUMBO: \n Place celery, onion, green bell pepper, and garlic into the work bowl of a food processor, and pulse until all vegetables are very finely chopped. Stir vegetables into the roux, and mix in sausage. Bring mixture to a simmer over medium-low heat, and cook until vegetables are tender, 10 to 15 minutes. Remove from heat, and set aside. Combine water and beef bouillon cubes in a large Dutch oven or soup pot and bring to a boil over medium-high heat. Stir until bouillon cubes dissolve, then whisk roux mixture into the boiling water. Reduce heat to a simmer, and mix in sugar, salt, hot pepper sauce, Cajun seasoning, bay leaves, thyme, stewed tomatoes, and tomato sauce. Simmer soup over low heat for 1 hour; mix in 2 teaspoons of file gumbo powder at the 45-minute mark. Meanwhile, melt 2 tablespoons bacon drippings in a skillet over medium heat. Add okra and vinegar and cook for 15 minutes; remove okra with a slotted spoon, and stir into the simmering gumbo. Mix in crabmeat, shrimp, and Worcestershire sauce, and simmer until flavors have blended, 45 more minutes. Stir in 2 more teaspoons of file gumbo powder just before serving. ",
         "Shrimp Alfredo Broccoli Bake: \n SERVINGS: 4 \n INGREDIENTS: \n 1 (8 ounce) package angel hair pasta \n 1 serving cooking spray \n 1 pound raw peeled and deveined shrimp, slightly thawed if frozen \n 2 cups chopped broccoli \n 1 & 1/2 cups Alfredo sauce \n 1/2 cup grated Parmesan cheese \n DIRECTIONS: \n Bring a large pot of lightly salted water to a boil. Cook angel hair in the boiling water, stirring occasionally, until tender yet firm to the bite, 4 to 5 minutes. Drain. Preheat oven to 350 degrees F (175 degrees C). Grease a 2-quart casserole dish with cooking spray. Cook and stir shrimp in a skillet over medium heat until slightly pink, 3 to 5 minutes. Add broccoli; cover skillet and let broccoli steam, about 5 minutes. Remove from heat. Spread angel hair pasta over the bottom of the prepared baking dish. Top with shrimp and broccoli. Pour Alfredo sauce over shrimp and broccoli; cover sauce with Parmesan cheese. Bake in the preheated oven until cheese is slightly browned, about 20 minutes.", 
         "Crispy Fried Fish: \n SERVINGS: 4 \n INGREDIENTS: \n 1 egg \n 1 & 1/2 cups beer \n 1 cup all-purpose flour \n 1 teaspoon garlic powder \n 1/2 teaspoon salt \n 1/2 teaspoon ground black pepper \n 1 pound cod fillets \n 2 cups crushed cornflake crumbs \n 1 teaspoon Cajun seasoning \n 1 quart oil for frying \n DIRECTIONS: \n In a medium bowl, beat together egg, beer, flour, garlic powder, salt, and pepper. Place cod in the bowl, and thoroughly coat with the mixture. In a separate medium bowl, mix the cornflake crumbs and Cajun seasoning. Dip the cod in the crumb mixture, and thoroughly coat all sides. In a large, heavy skillet or deep fryer, heat the oil to 365 degrees F (185 degrees C). Fry the fish until golden brown, and flesh is easily flaked with a fork."
        ]

salads = ["Asian Slaw: \n SERVINGS: 3, \n INGREDIENTS: \n DRESSING: \n 1/4 cup cashew or peanut butter, \n 2 tablespoons white miso paste, \n 2 tablespoons lime juice, \n 1 teaspoon sesame oil, \n 1 teaspoon grated ginger, \n 2 to 5 tablespoons water, or as needed \n FOR THE SALAD \n 6 to 7 cups shredded red and/or green cabbage, \n Mix of peppers: I used 3 Anaheim and 3 banana peppers; or use 1 red bell and 1 poblano. \n 2 scallions, chopped, \n 1/2 cup chopped cilantro, including stems, \n 1/2 cup fresh basil, Thai basil, and/or mint, \n 2 Thai chiles or 1 serrano pepper, diced, \n Sea salt, \n 1/4 cup toasted peanuts, pepitas, and/or sesame seeds, \n 1 ripe peach, thinly sliced, \n DIRECTIONS: \n Make the dressing: In a small bowl, whisk together the cashew butter, miso paste, lime juice, sesame oil, and ginger. Whisk in enough water to create a drizzable consistency. Set aside. In a dry cast-iron skillet over medium heat, char the peppers whole, rotating until the edges have a little char, about 2 minutes per side. Remove. When cool to the touch, slice in half lengthwise, remove the stem, ribbing, and seeds and slice horizontally into thin strips. In a large bowl, combine the cabbage, peppers, scallions, cilantro, basil, chiles, and ¾ of the dressing. Toss until combined. Add the remaining dressing, if desired, and season to taste with a few pinches of sea salt. Serve topped with the toasted nuts, seeds, and sliced peaches.",
        "Vegan Pasta Salad: \n SERVINGS: 7, \n INGREDIENTS: \n DRESSING: \n 1/4 cup tahini \n 1/4 cup almond milk or water \n 2 tablespoons lemon juice \n 2 tablespoons apple cider vinegar \n 1/2 tablespoon Dijon mustard \n 1/4 teaspoon maple syrup \n 1/2 teaspoon sea salt \n Freshly ground black pepper, to taste, FOR THE SALAD: \n 1 cup haricots verts, sliced in half lengthwise and cut into 1-inch pieces \n 8 ounces short curly pasta \n 2 medium yellow squash, spiralized or very thinly sliced \n 1 (14-ounce) can artichoke hearts, drained and sliced into quarters \n 3/4 cup cooked navy beans, drained and rinsed \n 1 heaping cup halved cherry tomatoes \n scant 1/4 cup thinly sliced red onion \n 1/4 cup Kalamata olives, sliced in half \n 1/2 cup chopped parsley \n 1/2 cup chopped basil \n 2 tablespoons sunflower seeds \n 1/2 teaspoon sea salt, more to taste \n DIRECTIONS: \n Bring a medium pot of salted water to a boil and place a bowl of ice water nearby. Blanch the haricots verts for 1 minute, then transfer to the ice water. Drain and pat dry. Bring a large pot of salted water to a boil. Prepare the pasta according to the instructions on the package, cooking just past al dente. Drain and rinse with cold water. Make the dressing: In a small-medium bowl, whisk together the milk, tahini, lemon juice, apple cider vinegar, mustard, maple syrup, salt, and pepper. In a very large bowl, combine the pasta, haricots verts, yellow squash, artichoke hearts, navy beans, cherry tomatoes, red onion, and olives. Toss with the dressing. Mix in the parsley, basil, and sunflower seeds. Season to taste with more salt (I add ½ teaspoon). Serve at room temperature or store in the fridge for up to 2 days. Season to taste before serving.",
         "Cherry Tomato Couscous Salad: \n SERVINGS: 4, \n INGREDIENTS: \n 4 cups cherry tomatoes, (half for roasting, half raw) \n Extra-virgin olive oil, for drizzling \n 1 cup dry Israeli couscous \n 1 tablespoon lemon juice, more if desired \n 1 garlic clove, minced \n Leaves from 6 sprigs fresh thyme, more for garnish \n 1 & 1/2 cups roasted chickpeas, tossed with 1/4 teaspoon smoked paprika before roasting \n 1/4 cup fresh basil, more for garnish \n 2 Persian cucumbers, thinly sliced \n 1/3 cup crumbled feta cheese \n Sea salt and freshly ground black pepper \n DIRECTIONS: \n Roast 2 cups of the cherry tomatoes according to this recipe. These can be made in advance and stored in the fridge for a few days. Cook the couscous according to the package directions until al dente, about 9 minutes. Drain and set aside to cool. In the bottom of a large bowl, combine 1 tablespoon of olive oil, the lemon juice, garlic, thyme, ¼ teaspoon salt, and several grinds of black pepper. Add the cooled couscous and toss. Slice the remaining raw cherry tomatoes in half and add them to the bowl with the roasted tomatoes, the chickpeas, basil, cucumbers, and feta. Top with more fresh herbs and a generous drizzle of olive oil. Season to taste."
        ]

burgers = ["Cheddar-Stuffed Burgers with Pickled Slaw and Fried Shallots: \n SERVINGS: 4 \n INGREDIENTS: \n Kosher salt \n 8 cups finely shredded green cabbage (from a 1 1/2-pound head) \n 1 cup distilled white vinegar \n 1 tablespoon sugar \n 2 tablespoons yellow mustard seeds \n Vegetable oil, for frying \n 5 large shallots, very thinly sliced crosswise and separated into rings \n 1/4 cup Wondra flour (see Note) \n 1 1/2 pounds ground beef chuck, preferably 85 percent lean \n 1 teaspoon onion powder \n 1 teaspoon garlic powder \n 1 teaspoon sweet smoked paprika \n 1 tablespoon Worcestershire sauce \n Freshly ground pepper \n 6 ounces extra-sharp cheddar, shredded \n 2 cups baby arugula \n 4 brioche buns, split and toasted \n DIRECTIONS: \n In a large bowl, toss 1 tablespoon of kosher salt with the cabbage and massage it until it softens and releases its liquid, about 4 minutes. Drain the cabbage in a colander and rinse it. Wipe out the bowl. Add the vinegar, sugar, mustard seeds, 1 cup of water and 1 tablespoon of salt. Add the cabbage to the vinegar mixture, toss to coat and place a plate on top to keep it submerged. Let stand at room temperature for 2 hours. Meanwhile, in a large saucepan, heat 1 1/2 inches of vegetable oil to 325°. In a medium bowl, toss the shallots with the Wondra flour. Fry the shallots all at once, stirring gently, until golden, about 7 minutes. Using a slotted spoon, transfer the shallots to a paper towel–lined plate to drain. Season the shallots with salt. Reserve the cooking oil. In a medium bowl, combine the ground beef with the onion powder, garlic powder, smoked paprika, Worcestershire sauce and 2 teaspoons each of kosher salt and ground pepper. Knead gently until thoroughly mixed. Form the beef into eight 4-inch patties. Press the shredded cheese into four 2 1/2-inch disks. Sandwich the cheese disks between the patties. Pinch the edges together to seal. Heat a grill pan or griddle. Brush the burgers with some of the shallot cooking oil and cook over moderate heat until browned on the bottom, about 3 minutes. Flip the burgers, invert a large heatproof bowl over them and cook until medium within and the cheese is melted, about 3 minutes longer. Mound the arugula on the bun bottoms and top with the burgers. Drain the pickled cabbage and mound some of it on the burgers; reserve the rest of the pickled cabbage for another use. Top with the fried shallots and the bun tops and serve.", 
         "BBQ Burgers: \n SERVINGS: 4 \n INGREDIENTS: \n 12 ounces beef chuck, coarsely ground \n 12 ounces beef sirloin, coarsely ground \n 2 teaspoons smoked paprika \n 1 teaspoon brown sugar \n 1/2 teaspoon cayenne \n 1/2 teaspoon coriander \n 1/2 teaspoon cumin \n 1/2 teaspoon garlic powder \n 1/2 teaspoon dry mustard powder \n 1/2 teaspoon onion powder \n 2 teaspoons Worcestershire sauce \n Kosher salt and freshly ground black pepper \n [For Serving:] Hamburger buns, coleslaw and potato chips (optional) DIRECTIONS: \n Heat a large cast-iron skillet over medium-high heat for 20 minutes. Gently mix the chuck and sirloin together in a large bowl, making sure not to overwork the mixture. Combine the paprika, brown sugar, cayenne, coriander, cumin, garlic powder, mustard powder and onion powder in a small bowl. Sprinkle the spice mixture over the beef along with the Worcestershire sauce and fold gently to combine. Form the beef into 4 3/4-inch-thick patties, each about 4-inches in diameter. Sprinkle them generously with salt and a pepper. Put the patties in the hot skillet (do not press down with a spatula). When the patties are seared and browned on one side, about 3 1/2 minutes, flip and cook on the other side until browned and the burgers are medium-rare, about 3 1/2 minutes more. Put the burgers on buns and top with coleslaw and serve with potato chips if using.",
         "Shrimp Burger with Old Bay Mayo: \n SERVINGS: 4 \n INGREDIENTS: \n FOR BURGER: \n 1 pound peeled and deveined medium shrimp \n 1/3 cup panko breadcrumbs \n 1 tablespoon lemon juice \n 1/2 teaspoon kosher salt \n 1/4 teaspoon garlic powder \n 1/4 teaspoon freshly ground black pepper \n 2 scallions, white and green parts, thinly sliced \n 1 large egg, lightly beaten \n 1/4 cup canola oil \n FOR OLD BAY MAYO: \n 1/2 cup mayonnaise \n 1 teaspoon to 1 tablespoon Old Bay seasoning \n 4 brioche buns, halved and lightly toasted \n Avocado slices, for topping \n Lettuce leaves, for topping \n Tomato slices, for topping \n DIRECTIONS: \n For the shrimp burgers: Coarsely chop half of the shrimp. Put the remaining shrimp in a food processor and pulse until smooth. Combine both shrimp in a large bowl with the breadcrumbs, lemon juice, salt, garlic powder, pepper, scallions and egg and mix. Refrigerate for 10 minutes, and then form into 4 patties. Refrigerate 10 more minutes. Heat the oil in a large cast-iron skillet over medium-high heat. Cook the burgers, about 3 minutes per side. For the Old Bay mayo: Combine the mayonnaise and Old Bay to taste in a small bowl. To serve, spread the buns with the mayo and place the burgers on the buns. Top the burgers with the avocado slices, lettuce leaves and tomato slices."
        ]

steaks = ["Porterhouse Steak: \n SERVINGS: 4 \n INGREDIENTS: \n One 36-ounce porterhouse steak, cut 2 inches thick \n Kosher salt \n Freshly ground black pepper \n 1 tablespoon unsalted butterMix apples and sugar well. Add oil, nuts, and eggs. Add vanilla and dry ingredients. Bake at 350 degrees for 40-45 minutes. Serve with whipped cream or top with cream cheese frosting. \n DIRECTIONS: \n Set a rack in a rimmed baking sheet. Season the steak with 1 tablespoon of salt and transfer to the rack. Refrigerate, uncovered, overnight. Let the steak come to room temperature 30 minutes before cooking. Preheat the oven to 400°. Heat a large cast-iron skillet until very hot, about 5 minutes. Pat the steak dry with paper towels and season with salt and pepper. Cook the steak over moderate heat until browned and crusty, about 3 minutes. Add the butter, turn the meat and transfer the skillet to the oven. Roast until an instant-read thermometer inserted in the thickest part registers 120° for medium-rare, 12 to 15 minutes. Transfer the steak to a work surface and let rest for 10 minutes before serving.",
         "Butter-Basted Rib Eye Steaks: \n SERVINGS: 4 \n INGREDIENTS: \n Two 1 1/4-pound, bone-in rib eye steaks \n Kosher salt \n Freshly ground pepper \n 2 tablespoons canola oil \n 4 tablespoons unsalted butter \n 4 thyme sprigs \n 3 garlic cloves \n 1 rosemary sprig \n DIRECTIONS: Season the rib eye steaks all over with salt and freshly ground pepper. Let the meat stand at room temperature for 30 minutes. In a large cast-iron skillet, heat the canola oil until shimmering. Add the steaks and cook over high heat until crusty on the bottom, about 5 minutes. Turn the steaks and add the butter, thyme, garlic and rosemary to the skillet. Cook over high heat, basting the steaks with the melted butter, garlic and herbs, until the steaks are medium-rare, 5 to 7 minutes longer. Transfer the steaks to a cutting board and let rest for 10 minutes. Cut the steaks off the bone, then slice the meat across the grain and serve.",
         "Garlic Butter Steak Bites: \n SERVINGS: 4 \n INGREDIENTS: \n 2 pounds beef strip steak (1-inch thick), cut into 1-inch pieces \n 2 teaspoons kosher salt, divided \n 1 teaspoon black pepper, divided \n 2 tablespoons vegetable oil \n 5 medium garlic cloves, finely chopped (3 tablespoons) \n 1/3 cup dry vermouth \n 4 tablespoons unsalted butter, cubed \n 2 teaspoons Worcestershire sauce \n 1 tablespoon finely chopped fresh flat-leaf parsley \n DIRECTIONS: \n Heat a large cast-iron skillet over medium-high. Sprinkle steak all over with 1 1/2 teaspoons of the salt and 1/2 teaspoon of the pepper. Add oil to skillet, and heat until shimmering. Add half of the steak pieces to skillet, keeping space between each piece. Cook, undisturbed, until browned and crispy on bottoms, about 1 minute. Flip steak pieces, and continue cooking until browned on other side, about 1 minute. Flip pieces again, and cook, turning occasionally, until most sides are browned and crispy and steak is almost medium-rare, 1 to 2 minutes. Transfer steak to a large bowl. Repeat cooking process with remaining steak pieces, transferring cooked steak to bowl with first batch; set aside. Do not wipe skillet clean. Reduce heat under skillet to medium; add garlic, and cook, stirring constantly, until golden brown, about 30 seconds. Add vermouth, and scrape up browned bits from bottom of skillet. Cook, stirring occasionally, until liquid is reduced to about 3 tablespoons, about 1 minute. Remove from heat; add butter, and stir until melted and creamy. Add Worcestershire sauce and remaining 1/2 teaspoon each salt and pepper. Pour mixture over steak pieces in bowl, and toss to coat. Transfer steak with butter sauce to a platter, and sprinkle with parsley. Serve immediately."
        ]

food_jokes= ["When potatoes have babies, what are they called? Tater tots!",
             "What do you call a fake noodle? IMPASTA!", 
            "What did the pecan say to the walnut? We're friends because we're both NUTS", 
            "Waffles are just pancakes with abs", "Why do beets always win? Because they are un-BEET-able", 
            "How do you compliment an avacado? BRAVOCADO!",
            "What are twins favorite fruits? Pears",
            "A guy just threw a milk at me. How dairy!?",
            ]
def handle_message(update, context):
    if Pork in update.message.text:
        update.message.reply_text(random.choice(porks))
        update.message.reply_text(random.choice(food_jokes))

    if Beef in update.message.text:
        update.message.reply_text(random.choice(food_jokes))
        update.message.reply_text(random.choice(beefs))

    if Chicken in update.message.text:
        update.message.reply_text(random.choice(chickens))
        update.message.reply_text(random.choice(food_jokes))

    if Pasta in update.message.text:
        update.message.reply_text(random.choice(pastas))
        update.message.reply_text(random.choice(food_jokes))
   
    if Taco in update.message.text:
        update.message.reply_text(random.choice(food_jokes))
        update.message.reply_text(random.choice(tacos))

    if Seafood in update.message.text:
        update.message.reply_text(random.choice(seafoods))
        update.message.reply_text(random.choice(food_jokes))

    if Salad in update.message.text:
        update.message.reply_text(random.choice(food_jokes))
        update.message.reply_text(random.choice(salads)) 

    if Burger in update.message.text:
        update.message.reply_text(random.choice(burgers))
        update.message.reply_text(random.choice(food_jokes))

    if Steak in update.message.text:
        update.message.reply_text(random.choice(steaks))
        update.message.reply_text(random.choice(food_jokes))    

    #text = str(update.message.text).lower()
    #response = R.responses(text)

    #update.message.reply_text(response)

def error(update, context):
    print(f"Update {update} caused error {context.error}")

def main():
    updater = Updater(keys.API_KEY, use_context=True)
    dp = updater.dispatcher

    dp.add_handler(CommandHandler("Start", start_command))
    dp.add_handler(CommandHandler("Help", help_command))
    dp.add_handler(CommandHandler("Recipes", recipes_command))
    dp.add_handler(CommandHandler("Vegan", vegan_command))
    dp.add_handler(CommandHandler("Cocktail", cocktail_command))

    dp.add_handler(MessageHandler(Filters.text, handle_message))

    dp.add_error_handler(error)

    updater.start_polling()
    updater.idle()

main()


